modLoader = "javafml"
loaderVersion = "[31,)"
issueTrackerURL = "${mod_issues_url}"
license = "MIT"

[[mods]]
modId = "oc2"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_url}"
#logoFile = "logo.png"
authors = "Sangar"
description = '''
Modern computers for the modern player.
'''

[[dependencies.oc2]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version_min},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.oc2]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version_min}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.oc2]]
modId = "oc2-sedna"
mandatory = true
versionRange = "[${oc2_sedna_version_min}]"
ordering = "NONE"
side = "BOTH"