modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/fnuecke/oc2/issues"
license = "MIT"

[[mods]]
modId = "oc2"
version = "${file.jarVersion}"
displayName = "OpenComputers II"
authors = "Sangar"
description = '''
Modern computers for the modern player.

This mod uses the Terminus Font under the Open Font License. The full license can be found in the JAR of this mod.
'''

[[dependencies.oc2]]
modId = "forge"
mandatory = true
versionRange = "[40.1.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.oc2]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
[[dependencies.oc2]]
modId = "sedna"
mandatory = true
versionRange = "[1.0.14,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.oc2]]
modId = "markdown_manual"
mandatory = true
versionRange = "[1.2.1,)"
side = "CLIENT"
